#!/usr/bin/env bash

# Find the PID of the Gunicorn process running on the specified port
pids=$(pgrep -f 'gunicorn.*myapp:app')
check=$(ps ax | grep gunicorn)

echo "pids: $pids"
echo "check: $check"

# check if any process IDs are found
if [ -n "$pids" ]; then
    # Terminate each process using kill command
    for pid in $pids; do
        kill -9 "$pid"
    done
    echo "All Gunicorn processes terminated."
else
    echo "No Gunicorn processes found."
    echo "$check"
    
fi